language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
script:
    - python manage.py test --settings=talks.settings_test
notifications:
    irc:
        channels:
            - "irc.ox.ac.uk#mox"
        on_success: change
