sudo: false
language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
script:
    - make test
notifications:
    irc:
        channels:
            - "irc.ox.ac.uk#mox"
        on_success: change
